server:
  port: 8080
nacos:
  config:
    server-addr: nacos.primihub.svc.cluster.local:8848
    namespace: 73f0641f-d121-473b-8600-b2e270dc7326
    max-retry: 3
    config-long-poll-timeout: 1000
    config-retry-time: 1000
    auto-refresh: true
    username: nacos
    password: nacos
    context-path: /nacos
    group: DEFAULT_GROUP
    file-extension: yaml
spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos.primihub.svc.cluster.local:8848
        namespace: 73f0641f-d121-473b-8600-b2e270dc7326
logging:
  level:
    root: info
