server:
  port: 8090
spring:
  application:
    name: platform
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace:
nacos:
  config:
    server-addr: localhost:8848
    namespace:
    max-retry: 3
    config-long-poll-timeout: 1000
    config-retry-time: 1000
    auto-refresh: true
    username: nacos
    password: nacos
    context-path: /nacos
    group: DEFAULT_GROUP
    file-extension: yaml
logging:
  level:
    root: info
