server:
  port: 8090
spring:
  application:
    name: platform
  rabbitmq:
    host: rabbitmq.primihub.svc.cluster.local
    port: 5672
    username: guest
    password: guest
    virtual-host: /test
  cloud:
    stream:
      bindings:
        singleTaskOutput:
          destination: singlTaskChannel
        singleTaskInput:
          destination: singlTaskChannel
          group: single
    nacos:
      discovery:
        server-addr: nacos.primihub.svc.cluster.local:8848
        namespace: 9be74df3-dd0d-46d7-a223-cbeaf4520769
nacos:
  config:
    server-addr: nacos.primihub.svc.cluster.local:8848
    namespace: 9be74df3-dd0d-46d7-a223-cbeaf4520769
    max-retry: 3
    config-long-poll-timeout: 1000
    config-retry-time: 1000
    auto-refresh: true
    username: nacos
    password: nacos
    context-path: /nacos
    group: DEFAULT_GROUP_1
    file-extension: yaml
logging:
  level:
    root: info
