server:
  port: 8090
spring:
  application:
    name: platform
  rabbitmq:
    host: rabbitmq.primihub.svc.cluster.local
    port: 5672
    username: primihub
    password: primihub
    virtual-host: /primihub
  cloud:
    stream:
      bindings:
        singleTaskOutput:
          destination: singlTaskChannel
        singleTaskInput:
          destination: singlTaskChannel
          group: single
    nacos:
      discovery:
        server-addr: nacos.primihub.svc.cluster.local:8848
        namespace:
nacos:
  config:
    server-addr: nacos.primihub.svc.cluster.local:8848
    namespace:
    max-retry: 3
    config-long-poll-timeout: 1000
    config-retry-time: 1000
    auto-refresh: true
    username: nacos
    password: nacos
    context-path: /nacos
    group: DEFAULT_GROUP
    file-extension: yaml
logging:
  level:
    root: info