---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: gateway
  namespace: primihub
  labels:
    k8s.kuboard.cn/layer: web
    k8s.kuboard.cn/name: gateway
  annotations:
    k8s.kuboard.cn/displayName: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s.kuboard.cn/layer: web
      k8s.kuboard.cn/name: gateway
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s.kuboard.cn/layer: web
        k8s.kuboard.cn/name: gateway
      annotations:
        kubectl.kubernetes.io/restartedAt: '2022-03-22T18:29:40+08:00'
    spec:
      containers:
        - name: gateway
          image: '192.168.99.10/primihub/gateway:43'
          command:
            - java
          args:
            - '-jar'
            - '-Dfile.encoding=UTF-8'
            - /applications/app.jar
            - '--spring.profiles.active=test'
            - '--server.port=8080'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  revisionHistoryLimit: 10
  paused: true
  progressDeadlineSeconds: 10
